# Generated by Django 3.2.12 on 2023-10-15 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20231015_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location_name', models.CharField(default='', max_length=50, verbose_name='from location name')),
                ('destination_location_name', models.CharField(default='', max_length=50, verbose_name='destination location name')),
                ('from_location_coordinates', models.JSONField(blank=True, default=dict, null=True, verbose_name='from location coordinates')),
                ('destination_location_coordinates', models.JSONField(blank=True, default=dict, null=True, verbose_name='destination location coordinates')),
                ('customer_info', models.JSONField(blank=True, default=dict, null=True, verbose_name='customer info')),
                ('email', models.CharField(default='', max_length=50, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='phone')),
                ('start_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='start time')),
                ('end_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='end time')),
                ('reg_no', models.BigIntegerField(db_index=True, default=0, verbose_name='reg no')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.driver')),
            ],
        ),
    ]
