# Generated by Django 3.2.12 on 2023-10-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='customer_info',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='phone',
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
