# Generated by Django 3.2.12 on 2023-10-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20231028_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='status',
        ),
        migrations.AddField(
            model_name='trip',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='is completed'),
        ),
    ]
