# Generated by Django 4.0.8 on 2023-10-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20231028_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='cost'),
        ),
    ]
