# Generated by Django 3.2.12 on 2023-10-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Driver'), (2, 'Customer'), (52124, 'admin')], default=52124, verbose_name='user type'),
        ),
    ]
