# Generated by Django 4.0.8 on 2023-10-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(200000000, 'admin'), (1, 'Driver'), (2, 'Customer')], default=200000000, verbose_name='user type'),
        ),
    ]
