# Generated by Django 3.2.12 on 2023-10-15 09:48

import accounts.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='name')),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='phone')),
                ('customer_code', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='customer code')),
                ('customer_id', models.UUIDField(verbose_name='customer id')),
                ('reg_no', models.BigIntegerField(db_index=True, default=0, verbose_name='reg no')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='name')),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='phone')),
                ('employee_id', models.UUIDField(verbose_name='employee id')),
                ('reg_no', models.BigIntegerField(db_index=True, default=0, verbose_name='reg no')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/no_image.jpg', upload_to=profiles.models.profile_directory_path, verbose_name='image')),
                ('old_image', models.ImageField(default='images/no_image.jpg', upload_to='', verbose_name='old image')),
                ('phone', models.BigIntegerField(default=0, unique=True, validators=[accounts.utils.validators.validate_phone_for_models], verbose_name='phone')),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
                ('join_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='join date')),
                ('business_name', models.CharField(default='', max_length=60, verbose_name='business name')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('reg_no', models.BigIntegerField(db_index=True, default=0, editable=False, unique=True, verbose_name='reg no')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(profiles.models.CommonProfileMethodsMixin, models.Model),
        ),
    ]
