# Generated by Django 3.2.12 on 2023-10-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='last name')),
                ('email', models.CharField(default='', max_length=50, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='phone')),
                ('reg_no', models.BigIntegerField(db_index=True, default=0, verbose_name='reg no')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='phone'),
        ),
    ]
