# Generated by Django 3.2.12 on 2023-10-15 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231015_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_location_coordinates',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='current location coordinates'),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_location_name',
            field=models.CharField(default='', max_length=50, verbose_name='current location name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='join_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='join date'),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_location_coordinates',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='current location coordinates'),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_location_name',
            field=models.CharField(default='', max_length=50, verbose_name='current location name'),
        ),
        migrations.AddField(
            model_name='driver',
            name='join_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='join date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reg_no',
            field=models.BigIntegerField(db_index=True, default=0, unique=True, verbose_name='reg no'),
        ),
    ]
