# Generated by Django 3.2.12 on 2023-10-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=15, unique=True, verbose_name='day name')),
                ('choice_id', models.IntegerField(default=0, verbose_name='choice id')),
            ],
        ),
        migrations.CreateModel(
            name='MySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=300, unique=True, verbose_name='name')),
                ('reset_tokens', models.BooleanField(default=False, verbose_name='reset tokens')),
                ('signups', models.BooleanField(default=True, verbose_name='signups')),
                ('maintenance', models.BooleanField(default=True, verbose_name='maintenance')),
                ('allow_contact', models.BooleanField(default=True, verbose_name='allow contact')),
                ('delete_sessions', models.BooleanField(default=False, verbose_name='delete sessions')),
            ],
        ),
    ]
